version: '3'

volumes:
  prometheus_data: {}
  grafana_storage: {}

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - gateway
    volumes:
      - ./data/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - gateway
    user: "104"
    depends_on:
      - prometheus
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./data/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./data/grafana/config.monitoring
    restart: always

  activemq:
    image: symptoma/activemq:latest
    container_name: 'activemq'
    networks:
      - gateway
    ports:
      - "61616:61616" # broker (admin:adminactivemq)(amq:amq)
      - "8161:8161"   # web    http://localhost:8161/admin (admin:admin)
    volumes:
      - ./data/activemq/data:/data/activemq
      - ./data/activemq/log:/var/log/activemq

networks:
  gateway: { }