activemq:
  broker-url: tcp://localhost:61616
  message-queue: message-queue

application:
  narayana:
    enabled: true
logging:
  level:
    com:
      arjuna: TRACE
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG

narayana:
  onePhaseCommit: true
server:
  port: 8080
  tomcat:
    threads:
      min-spare: 11
      max: 201
spring:
  datasource:
    primary:
      url: jdbc:oracle:thin:@lnvdevsbx1:1527:SBXDEVS
      username: EBH_ESL_ACCOUNTS_PROXY
      password: sbxdevs
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        minimum-idle: 11
        maximum-pool-size: 101

  jms:
    listener:
      auto-startup: false
  h2:
    console:
      enabled: false
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  jta:
    log-dir: ./transaction-logs
    transaction-manager-id: ${random.uuid}
  task:
    execution:
      pool:
        core-size: 64

management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"