activemq:
    broker-url: tcp://localhost:61616
    message-queue: message-queue

application:
    narayana:
        enabled: false
logging:
    level:
        com:
            arjuna: TRACE
        org:
            springframework:
                orm:
                    jpa: DEBUG
                transaction: DEBUG

narayana:
    onePhaseCommit: false
server:
    port: 8081
    tomcat:
        threads:
            min-spare: 11
            max: 201
spring:
    datasource:
        primary:
            driver-class-name: org.h2.Driver
            password: ''
            url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
            username: sa
            hikari:
                maximum-pool-size: 101
                minimum-idle: 11

    jms:
        listener:
            auto-startup: false
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: create
        open-in-view: false
    jta:
        log-dir: ./transaction-logs
        transaction-manager-id: ${random.uuid}

management:
    endpoints:
        web:
            exposure:
                include: "*"